name: Build Flatpak Package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          
      - name: Set up Flatpak
        run: |
          sudo apt-get install -y flatpak flatpak-builder
          sudo add-apt-repository ppa:flatpak/stable

      - name: Install repository Flatpak
        run: |
          flatpak --user remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

      - name: Install SDK
        run: |
          flatpak install -y flathub org.freedesktop.Platform//22.08 org.freedesktop.Sdk//22.08

      - name: Build Flatpak package
        run: flatpak-builder --force-clean build-dir src/org.flatpak.HelloApp.yml

      - name: Flatpak-builder
        run: | 
          flatpak-builder --user --install --force-clean build-dir src/org.flatpak.HelloApp.yml

      - name: Delete repository
        run: | 
          flatpak uninstall -y org.flatpak.HelloApp
          flatpak remote-delete helloapp-origin

      - name: Flatpak repository
        run: | 
          flatpak-builder --repo=myrepo --force-clean build-dir src/org.flatpak.HelloApp.yml

      - name: List applications
        run: | 
          flatpak list

      - name: Search applications
        run: | 
          flatpak search org.flatpak.HelloApp

      - name: List repository
        run: | 
          flatpak remotes

      - name: Install application from the repository
        run: | 
          flatpak --user remote-add --no-gpg-verify myrepo myrepo
          flatpak --user install myrepo org.flatpak.HelloApp

      - name: Archive build output
        run: |
          tar -czvf flatpak-build-output.tar.gz build-dir

      - name: Upload Flatpak build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: flatpak-build-output
          path: flatpak-build-output.tar.gz