name: Build Flatpak Package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'  # Exemplo de distribuição, substitua conforme necessário

#      - name: Build JAR with Gradle
#        run: |
#         ./gradlew assemble
          
      - name: Set up Flatpak
        run: |
          sudo apt-get update
          sudo apt-get install -y flatpak flatpak-builder
          flatpak --user remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          flatpak --user install -y flathub org.freedesktop.Platform//21.08
          flatpak --user install -y flathub org.freedesktop.Sdk//21.08   

      - name: Install repository Flatpak
        run: |
          flatpak remote-add --if-not-exists --user flathub https://dl.flathub.org/repo/flathub.flatpakrepo

      - name: Prepare Flatpak build environment
        run: |
          mkdir -p build-dir
          mkdir -p files
          cp composeApp/build/libs/composeApp-desktop.jar files/composeApp-desktop.jar

      - name: Enter directory and list files
        run: |
          cd files 
          ls -la

      - name: Build Flatpak package
        run: flatpak-builder --force-clean build-dir com.flatpak.json

      - name: Flatpak-builder
        run: | 
          cat com.flatpak.json > build-dir/com.flatpak.json
          flatpak-builder --force-clean --repo=repo build-dir

      - name: Publish Flatpak package
        run: |
          flatpak build-bundle repo myapp.flatpak com.example.MyApp
          
      - name: Upload Flatpak package
        uses: actions/upload-artifact@v3
        with:
          name: myapp-flatpak
          path: myapp.flatpak
